# -*- mode: ruby -*-
# vi: set ft=ruby :
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

     config.vm.provider "virtualbox" do |v|
       v.memory = 2048
       v.cpus = 2
     end
     config.vm.box = "bento/ubuntu-16.04"

     config.vm.network "forwarded_port", guest: 80, host: 8080
     config.vm.network "forwarded_port", guest: 8500, host: 8500
     config.vm.provision "shell", inline: <<-SHELL
     apt-get update -y
     apt-get install docker docker-compose -y
     apt-get install unzip -y

     ##Inicia o docker
     /etc/init.d/docker start
     update-rc.d docker enable 2

     ##Faz o pull das imagens que serao utilizadas
     docker pull fernandopereira/nginx-consul-template
     docker pull progrium/consul
     docker pull gliderlabs/registrator

     #Rodando o container do Consul para controlar os nodes e interagir com o Nginx
     docker run -dit --restart unless-stopped -p 8400:8400 -p 8500:8500 -p 53:53/udp -p 8600:53/udp -h consul --name consul progrium/consul -server -advertise=127.0.0.1 -bootstrap=1

     #Rodando o Nginx+consul+consul-template
     docker run -dit --link consul -p 80:80 --restart unless-stopped fernandopereira/docker-nginx-consul

     ##Rodando o container do register para monitorar
     docker run -dit --link consul --restart unless-stopped --name=registrator --volume=/var/run/docker.sock:/tmp/docker.sock gliderlabs/registrator:latest consul://127.0.0.1:8500

     #Rodando o container o Nginx com LB + consul template
     docker run -dit --link consul --restart unless-stopped -h $hostname --name $hostname -p 3000:3000 -ti fernandopereira/nodejs
  SHELL
end

